// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: my.proto

package im.turms.server.common.access.client.dto.model.conversation;

public final class GroupConversationOuterClass {
    private GroupConversationOuterClass() {}
    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_im_turms_proto_GroupConversation_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_im_turms_proto_GroupConversation_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_im_turms_proto_GroupConversation_MemberIdToReadDateEntry_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_im_turms_proto_GroupConversation_MemberIdToReadDateEntry_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }
    private static  com.google.protobuf.Descriptors.FileDescriptor
            descriptor;
    static {
        java.lang.String[] descriptorData = {
                "\n\010my.proto\022\016im.turms.proto\"\351\001\n\021GroupConv" +
                        "ersation\022\020\n\010group_id\030\001 \001(\003\022\026\n\016unReadMsgC" +
                        "ount\030\002 \001(\003\022\024\n\014hasMsgUnRead\030\003 \001(\010\022Y\n\026memb" +
                        "er_id_to_read_date\030\004 \003(\01329.im.turms.prot" +
                        "o.GroupConversation.MemberIdToReadDateEn" +
                        "try\0329\n\027MemberIdToReadDateEntry\022\013\n\003key\030\001 " +
                        "\001(\003\022\r\n\005value\030\002 \001(\003:\0028\001BB\n;im.turms.serve" +
                        "r.common.access.client.dto.model.convers" +
                        "ationP\001\272\002\000b\006proto3"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[] {
                        });
        internal_static_im_turms_proto_GroupConversation_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_im_turms_proto_GroupConversation_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_im_turms_proto_GroupConversation_descriptor,
                new java.lang.String[] { "GroupId", "UnReadMsgCount", "HasMsgUnRead", "MemberIdToReadDate", });
        internal_static_im_turms_proto_GroupConversation_MemberIdToReadDateEntry_descriptor =
                internal_static_im_turms_proto_GroupConversation_descriptor.getNestedTypes().get(0);
        internal_static_im_turms_proto_GroupConversation_MemberIdToReadDateEntry_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_im_turms_proto_GroupConversation_MemberIdToReadDateEntry_descriptor,
                new java.lang.String[] { "Key", "Value", });
    }

    // @@protoc_insertion_point(outer_class_scope)
}
