// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: my.proto

package im.turms.server.common.access.client.dto.model.conversation;

public interface GroupConversationOrBuilder extends
        // @@protoc_insertion_point(interface_extends:im.turms.proto.GroupConversation)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 group_id = 1;</code>
     * @return The groupId.
     */
    long getGroupId();

    /**
     * <code>int64 unReadMsgCount = 2;</code>
     * @return The unReadMsgCount.
     */
    long getUnReadMsgCount();

    /**
     * <code>bool hasMsgUnRead = 3;</code>
     * @return The hasMsgUnRead.
     */
    boolean getHasMsgUnRead();

    /**
     * <code>map&lt;int64, int64&gt; member_id_to_read_date = 4;</code>
     */
    int getMemberIdToReadDateCount();
    /**
     * <code>map&lt;int64, int64&gt; member_id_to_read_date = 4;</code>
     */
    boolean containsMemberIdToReadDate(
            long key);
    /**
     * Use {@link #getMemberIdToReadDateMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.Long, java.lang.Long>
    getMemberIdToReadDate();
    /**
     * <code>map&lt;int64, int64&gt; member_id_to_read_date = 4;</code>
     */
    java.util.Map<java.lang.Long, java.lang.Long>
    getMemberIdToReadDateMap();
    /**
     * <code>map&lt;int64, int64&gt; member_id_to_read_date = 4;</code>
     */
    long getMemberIdToReadDateOrDefault(
            long key,
            long defaultValue);
    /**
     * <code>map&lt;int64, int64&gt; member_id_to_read_date = 4;</code>
     */
    long getMemberIdToReadDateOrThrow(
            long key);
}
