turms:
  cluster:
    connection:
      client:
        ssl:
          enabled: false # Enable SSL if needed
          enabled-protocols: TLSv1.2,TLSv1.3
          key-store: classpath:keystore-test.p12 # keytool -genkeypair -keyalg RSA -keysize 2048 -validity 3650 -alias turms -keystore keystore-test.p12 -storetype PKCS12 -storepass imturms
          key-store-type: PKCS12
          key-store-password: imturms
          key-alias: turms
      server:
        ssl:
          enabled: false # Enable SSL if needed
          enabled-protocols: TLSv1.2,TLSv1.3
          key-store: classpath:keystore-test.p12 # keytool -genkeypair -keyalg RSA -keysize 2048 -validity 3650 -alias turms -keystore keystore-test.p12 -storetype PKCS12 -storepass imturms
          key-store-type: PKCS12
          key-store-password: imturms
          key-alias: turms
  gateway:
    websocket:
      enabled: true
      port: 10510
      ssl:
        enabled: false # Enable SSL if needed. Make sure to mutate HTTP requests to HTTPS requests, or Netty will throw NotSslRecordException
        enabled-protocols: TLSv1.2,TLSv1.3
        key-store: classpath:keystore-test.p12 # keytool -genkeypair -keyalg RSA -keysize 2048 -validity 3650 -alias turms -keystore keystore-test.p12 -storetype PKCS12 -storepass imturms
        key-store-type: PKCS12
        key-store-password: imturms
        key-alias: turms
    tcp:
      port: 11510
      ssl:
        enabled: false # Enable SSL if needed
        enabled-protocols: TLSv1.2,TLSv1.3
        key-store: classpath:keystore-test.p12 # keytool -genkeypair -keyalg RSA -keysize 2048 -validity 3650 -alias turms -keystore keystore-test.p12 -storetype PKCS12 -storepass imturms
        key-store-type: PKCS12
        key-store-password: imturms
        key-alias: turms
    udp:
      # Disable UDP currently until clients support UDP
      enabled: false
      port: 12510

# Spring configuration
spring:
  profiles:
    active: dev
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
      - org.springframework.boot.autoconfigure.mongo.MongoReactiveAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisReactiveAutoConfiguration
  netty:
    leak-detection: simple